# Generated by Django 5.0.6 on 2024-11-27 13:53

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=Gallery.models.user_post_photo_path),
        ),
    ]
