# Generated by Django 5.0.6 on 2024-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_rename_title_gallery_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_title',
            field=models.CharField(blank=True, default='Untitled Gallery', max_length=200),
        ),
    ]
