# Generated by Django 5.0.6 on 2024-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_alter_gallery_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
