# Generated by Django 5.0.6 on 2024-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_alter_gallery_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_title',
        ),
    ]
